### ISSUE TITLE
unexpected "bucket_exists.py" output with "Play" server

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-py#314] opened 2015-12-07 17:45 UTC
I am trying to execute minio-py examples on our minio play server & on executing bucket_exists.py, i am getting this error.

```
$python bucket_exists.py
/Users/koolhead17/Desktop/workdir/testvirtualenv/venv/lib/python2.7/site-packages/urllib3-1.12-py2.7.egg/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Traceback (most recent call last):
File "bucket_exists.py", line 22, in <module>
print client.bucket_exists('kline')
File "build/bdist.macosx-10.9-intel/egg/minio/api.py", line 240, in bucket_exists
File "build/bdist.macosx-10.9-intel/egg/urllib3/request.py", line 68, in request
File "build/bdist.macosx-10.9-intel/egg/urllib3/request.py", line 89, in request_encode_url
File "build/bdist.macosx-10.9-intel/egg/urllib3/poolmanager.py", line 161, in urlopen
File "build/bdist.macosx-10.9-intel/egg/urllib3/connectionpool.py", line 588, in urlopen
urllib3.exceptions.SSLError: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

**Comment by harshavardhana** [comment] 2015-12-08 01:00
Not able to reproduce can you do 'pip install urllib3 --upgrade' ?

**Comment by harshavardhana** [comment] 2015-12-17 01:42
Fixed in current master.

**Closed by harshavardhana** 2015-12-17 01:42 UTC
