### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by messense** [minio/minio-py#519] opened 2017-05-09 03:00 UTC
```
Traceback (most recent call last):
  File "/home/prerender/venv/lib/python3.6/site-packages/prerender/app.py", line 129, in handle_request
    data = await cache.get(url, format)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/prerender/venv/lib/python3.6/site-packages/prerender/cache/s3.py", line 47, in get
    res = await loop.run_in_executor(None, self.client.get_object, S3_BUCKET, path)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/prerender/venv/lib/python3.6/site-packages/minio/api.py", line 781, in get_object
    object_name)
  File "/home/prerender/venv/lib/python3.6/site-packages/minio/api.py", line 1486, in _get_partial_object
    preload_content=False)
  File "/home/prerender/venv/lib/python3.6/site-packages/minio/api.py", line 1900, in _url_open
    object_name).get_exception()
  File "/home/prerender/venv/lib/python3.6/site-packages/minio/error.py", line 141, in __init__
    self._handle_error_response(bucket_name)
  File "/home/prerender/venv/lib/python3.6/site-packages/minio/error.py", line 161, in _handle_error_response
    if not self._response.data:
  File "/home/prerender/venv/lib/python3.6/site-packages/urllib3/response.py", line 188, in data
    return self.read(cache_content=True)
  File "/home/prerender/venv/lib/python3.6/site-packages/urllib3/response.py", line 380, in read
    data = self._fp.read()
  File "/usr/lib/python3.6/http/client.py", line 456, in read
    return self._readall_chunked()
  File "/usr/lib/python3.6/http/client.py", line 566, in _readall_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/lib/python3.6/http/client.py", line 612, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
AttributeError: 'NoneType' object has no attribute 'read'
```

When error occurs, access `self._response.data` in `ResponseError._handle_error_response` may result in another exception.

**Comment by harshavardhana** [comment] 2017-05-09 03:05
> When error occurs, access self._response.data in ResponseError._handle_error_response may result in another exception.

Is this because you have a timeout? looks like the read() method is missing which is strange.

**Comment by messense** [comment] 2017-05-09 03:30
The http request which calls minio has a timeout set to 60s.

**Comment by harshavardhana** [comment] 2017-05-09 03:58
> The http request which calls minio has a timeout set to 60s.

I see will take a look.. @messense

**Comment by harshavardhana** [comment] 2017-05-13 07:19
Not able to reproduce this @messense - do you have any more information?

**Comment by messense** [comment] 2017-05-13 07:22
https://sentry.bosondata.net/share/issue/33302e323532363432/

**Comment by messense** [comment] 2017-05-13 07:25
@harshavardhana I wonder is `minio-py` thread safe?

**Comment by harshavardhana** [comment] 2017-05-13 07:28
> https://sentry.bosondata.net/share/issue/33302e323532363432/
>  

This has got nothing to do with thread safety. Looks like it is a known problem https://github.com/kennethreitz/requests/issues/3174 in urllib3 how often does this occur?

**Comment by messense** [comment] 2017-05-13 07:31
![image](https://cloud.githubusercontent.com/assets/1556054/26023557/2a4359fe-37f1-11e7-9026-044151a04033.png)

**Comment by harshavardhana** [comment] 2017-05-13 07:33
what is your urllib3 version?

**Comment by messense** [comment] 2017-05-13 07:35
urllib3==1.21.1

**Comment by hackintoshrao** [comment] 2017-05-18 23:39
Is this issue witnessed while using get object ?

**Comment by messense** [comment] 2017-05-19 03:46
@hackintoshrao Yes.

**Comment by hackintoshrao** [comment] 2017-05-20 12:14
@messense : Not able to reproduce this. Have you got any snippet of code to reproduce this ?

**Comment by messense** [comment] 2017-05-20 12:15
The code is here: https://github.com/bosondata/chrome-prerender/blob/master/prerender/cache/s3.py#L47

**Comment by hackintoshrao** [comment] 2017-05-22 06:35
@messense : Can you specify set of steps to reproduce this ? I assume this issue is occurring while using `prerender`. It'll be great if you can specify clear sequence of steps to reproduce this.

**Comment by messense** [comment] 2017-05-22 06:48
I haven't got the specify set of steps to reproduce this, only see these errors in Sentry sometimes. 

It's not a very big issue for us since we can retry when exception occurred. (In last 14 days, it occurred only ~650 times.)

**Comment by messense** [comment] 2017-05-22 06:49
BTW, I am using minio-py to access AWS S3 instead of minio.

**Comment by hackintoshrao** [comment] 2017-05-22 07:15
So its an occasional issue. I'll try to use the functions used [here](https://github.com/bosondata/chrome-prerender/blob/master/prerender/cache/s3.py) to create an independent snippet upload to Amazon S3 and see if I could reproduce it.

**Comment by poornas** [comment] 2017-06-20 01:52
@messense, do you still see this issue? We haven't been able to reproduce this error at our end. Are you on the latest version of minio-py?

**Comment by messense** [comment] 2017-06-20 02:00
I'll upgrade to latest version and see if it's resolved.

**Comment by poornas** [comment] 2017-06-28 20:21
@messense , closing this issue for now. Please reopen if you still see this with latest version of minio-py.

**Closed by poornas** 2017-06-28 20:21 UTC
Labels: priority: high, working as intended
