### ISSUE TITLE
Errors while running Azure and S3 tests on Mint 

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio-py#671] opened 2018-06-20 22:40 UTC
I got the following error while running Azure gateway tests for minio-py:
```
{
  "status": "FAIL",
  "duration": 3,
  "name": "minio-py:test_make_bucket_with_region",
  "function": "make_bucket(bucket_name, location)",
  "args": {
    "bucket_name": "minio-py-test-7e57f9a5-e001-4cb5-ae11-330dd321a4aa",
    "location": "us-west-1"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 188, in test_make_bucket_with_region\n    client.make_bucket(bucket_name, location)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 289, in make_bucket\n    raise ResponseError(response, method, bucket_name).get_exception()\nminio.error.ResponseError: ResponseError: code: AuthorizationHeaderMalformed, message: The authorization header is malformed; the region is wrong; expecting 'us-east-1'., bucket_name: None, object_name: None, request_id: 1539FF6772ED30E5, host_id: 3L137, region: us-east-1\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1710, in main\n    test_make_bucket_with_region(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 196, in test_make_bucket_with_region\n    raise Exception(err)\nException: ResponseError: code: AuthorizationHeaderMalformed, message: The authorization header is malformed; the region is wrong; expecting 'us-east-1'., bucket_name: None, object_name: None, request_id: 1539FF6772ED30E5, host_id: 3L137, region: us-east-1\n",
  "message": "ResponseError: code: AuthorizationHeaderMalformed, message: The authorization header is malformed; the region is wrong; expecting 'us-east-1'., bucket_name: None, object_name: None, request_id: 1539FF6772ED30E5, host_id: 3L137, region: us-east-1"
}
```

**Comment by kaankabalak** [comment] 2018-06-20 23:08
I got a similar error while running S3 gateway tests as well:
```
{
  "name": "minio-py:test_make_bucket_with_region",
  "function": "make_bucket(bucket_name, location)",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 188, in test_make_bucket_with_region\n    client.make_bucket(bucket_name, location)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 289, in make_bucket\n    raise ResponseError(response, method, bucket_name).get_exception()\nminio.error.ResponseError: ResponseError: code: AuthorizationHeaderMalformed, message: The authorization header is malformed; the region is wrong; expecting 'us-east-1'., bucket_name: None, object_name: None, request_id: 153A00ED61CAFFDE, host_id: 3L137, region: us-east-1\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1710, in main\n    test_make_bucket_with_region(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 196, in test_make_bucket_with_region\n    raise Exception(err)\nException: ResponseError: code: AuthorizationHeaderMalformed, message: The authorization header is malformed; the region is wrong; expecting 'us-east-1'., bucket_name: None, object_name: None, request_id: 153A00ED61CAFFDE, host_id: 3L137, region: us-east-1\n",
  "args": {
    "bucket_name": "minio-py-test-a1e0f491-dfe7-411f-ac0b-dd594b698ff5",
    "location": "us-west-1"
  },
  "message": "ResponseError: code: AuthorizationHeaderMalformed, message: The authorization header is malformed; the region is wrong; expecting 'us-east-1'., bucket_name: None, object_name: None, request_id: 153A00ED61CAFFDE, host_id: 3L137, region: us-east-1",
  "duration": 3
}
```

**Comment by smouli** [comment] 2018-06-21 18:01
We are unable to reproduce the error as seen below:

$ aws s3api get-bucket-location --bucket minio-py-test-7e57f9a5-e001-4cb5-ae11-330dd321a4aa
{
    "LocationConstraint": "us-west-1"
}
$ aws s3api get-bucket-location --bucket minio-py-test-a1e0f491-dfe7-411f-ac0b-dd594b698ff5
{
    "LocationConstraint": "us-west-1"
}

**Comment by harshavardhana** [comment] 2018-06-21 18:05
The issue is in minio-py tests, this test shouldn't be run on any endpoint other than AWS S3 itself directly.

**Comment by kannappanr** [comment] 2018-06-26 17:42
Not seen after the recent changes in Gateway and Azure code. Closing this issue as fixed.

**Closed by kannappanr** 2018-06-26 17:42 UTC
Labels: priority: high
