### ISSUE TITLE
Inconsistent handling of custom metadata information

### ISSUE THREAD

**Issue by araujof** [minio/minio-py#662] opened 2018-06-12 13:19 UTC
Hi all, 

Please kindly take a look at this open issue in the main minio repo: https://github.com/minio/minio/issues/6027.

Thanks!

**Comment by ebozduman** [comment] 2018-06-15 00:02
Closing as this is duplicate of issue minio/minio#6027 (which was also a duplicate of the fixed issue #655)

**Closed by ebozduman** 2018-06-15 00:02 UTC
Labels: duplicate, priority: medium, triage
