### ISSUE TITLE
You are not using the length param in Minio.put_object, why not make it optional?

### ISSUE THREAD

**Issue by wonderbeyond** [minio/minio-py#650] opened 2018-04-15 14:20 UTC
See: https://github.com/minio/minio-py/blob/master/minio/api.py#L797
```python
    def put_object(self, bucket_name, object_name, data, length,
                   content_type='application/octet-stream',
                   metadata=None):
        # ...
        return self._do_put_object(bucket_name, object_name,
                                   current_data, len(current_data),
                                   metadata=metadata)
```

And getting the length of when doing put_object is tedious and make no much sense.

For example:

```python
buf = io.BytesIO(b'Hello, World!')
length = buf.getbuffer().nbytes
ossc.put_object('default', 'test-blob', buf, length)
```

Which makes too much noise to my code, I probably should care whether the `buf` object is an BytesIO or other file-like object.

Thanks!

**Comment by wonderbeyond** [comment] 2018-04-15 14:50
It' fair now, since I've made two wrapper classes for ease:

```python
import six
from minio import Minio

class Bucket(object):
    def __init__(self, client, bucket_name):
        self.client = client
        self.bucket_name = bucket_name

    def __repr__(self):
        return '<OSS({}).Bucket({})>'.format(
            self.client._endpoint_url,
            self.bucket_name,
        )

    def ensure(self, **kwargs):
        if not self.client.bucket_exists(self.bucket_name):
            self.client.make_bucket(self.bucket_name, **kwargs)

    def get_object(self, key, **kwargs):
        return self.client.get_object(self.bucket_name, key, **kwargs)

    def put_object(self, key, data,
                   content_type='application/octet-stream',
                   metadata=None,
                   **kwargs):
        """
        Add a new object OSS.

        :param key: Name of new object.
        :param data: Contents to upload, readable or bytes
        """

        assert 'length' not in kwargs, 'I dont care the length!'

        if callable(getattr(data, 'read', None)):
            data = data.read()

        if isinstance(data, six.string_types):
            data = data.encode('utf-8')  # to bytes

        metadata = metadata or {}

        return self.client._do_put_object(
            self.bucket_name, key, data, len(data), **kwargs
        )


class OSSC(Minio):
    """Object Storage Service Client"""

    def bucket(self, bucket_name):
        return Bucket(self, bucket_name)
```

Then I can:

```python
bkt = ossc.bucket('default')

# Write text
text = 'Hello World'
bkt.put_object('hello', text)

# Write bytes
blob = b'Hello World -- bytes'
bkt.put_object('hello', blob)

# Write from file-object
with open('/home/wonder/lab/t.txt', 'r') as f:
    bkt.put_object('hello', f)

# Write BytesIO
buf = io.BytesIO(b'Hello World -- BytesIO')
bkt.put_object('hello', buf)
```

Thanks for the underlying work!

**Comment by poornas** [comment] 2018-04-17 05:49
@wonderbeyond, if you look at https://github.com/minio/minio-py/blob/master/minio/api.py#L790 , the stream size read requires length. The put_object call requires length to enable optimal chunking of large uploads

**Comment by wonderbeyond** [comment] 2018-04-17 06:37
However you can just call `data.read()` to get the full data, isn't it always a desired behaviour?

**Comment by poornas** [comment] 2018-05-22 21:21
@wonderbeyond, sorry about the late reply. Using data.read() to get the stream size here  would load the entire data into memory. it is expected that the calling application knows the size of data being processed rather than the sdk assuming that responsibility. Please let us know if there are additional questions, or if this issue can be closed.

**Comment by wonderbeyond** [comment] 2018-05-24 02:12
I meant you can just make it an **optional** parameter, since calculating the size of a stream at application side maybe a burden. look the ugly code below:

```
buf = io.BytesIO(b'Hello, World!')
length = buf.getbuffer().nbytes
```

And different file-like object may have different interface to get its size, some maybe impossible without reading out.

**Comment by harshavardhana** [comment] 2018-05-24 02:20
> I meant you can just make it an optional parameter, since calculating the size of a stream at application side maybe a burden. look the ugly code below:
> 
> buf = io.BytesIO(b'Hello, World!')
> length = buf.getbuffer().nbytes
> And different file-like object may have different interface to get its size, some maybe impossible without reading out.

We don't have much control on the S3 API behavior which requires content length, so providing right length is upto you.

**Comment by deekoder** [comment] 2018-05-30 02:41
@wonderbeyond closing this for now as working as intended. It's a bit ugly I agree to do the computation on the application side. For now we will keep the api without this optional param.

**Closed by deekoder** 2018-05-30 02:41 UTC
Labels: priority: medium, triage, working as intended

**Comment by gerritsangel** [comment] 2020-11-19 18:58
Hello,

I was wondering on how to upload a stream of unknown size  with the Minio Python SDK.

The Java SDK supports uploading of unknown size streams, so I'm a bit surprised that the Python SDK doesn't seem to support it.

(See https://minio-java.min.io/io/minio/MinioClient.html#putObject-io.minio.PutObjectArgs-):

```java
 // Upload unknown sized input stream.
 minioClient.putObject(
     PutObjectArgs.builder().bucket("my-bucketname").object("my-objectname").stream(
             inputStream, -1, 10485760)
         .contentType("video/mp4")
         .build());
```

Here, the file part size must be manually specified, but the stream length can be set as -1.

is there any protocol issue that would prevent the Python SDK to support unknown streams? Reading the entire stream into memory is difficult if it is a large file, especially on devices with few memory :-(

**Comment by balamurugana** [comment] 2020-11-19 19:10
@gerritsangel The support is added in the master https://github.com/minio/minio-py/blob/master/minio/api.py#L1252

We will make new release soon.
