### ISSUE TITLE
Memory leak during uploading file frequently 

### ISSUE THREAD

**Issue by nnehdi** [minio/minio-py#627] opened 2018-02-18 07:54 UTC
We are uploading lots of file frequently in Minio and we saw we have a memory leak. After checking it with memory_profiler we understood that the problem was the Minio connector.
This is the code that we used to profile the memory usage and the result shows that the memory usage  is increasing with time.  
```
import io
import os

from memory_profiler import profile
from minio import Minio

@profile
def _upload_file():
    object_path = ".../6_meg_file.mp3"
    object_name = "test/6_meg_file.mp3"
    bucket_name = "tst"
    file_size = os.stat(object_path).st_size
    with io.open(object_path, mode='rb') as file_data:
        return minio_client.put_object(bucket_name, object_name, file_data, file_size)

minio_client = Minio('<ip>', '<hidden>', '<hidden>', secure=False)
while True:
    result = _upload_file()
    print(result)
```

This is the result that shows memory leakage.
```


Line #    Mem usage    Increment   Line Contents
================================================
    92     22.1 MiB     22.1 MiB   @profile
    93                             def _upload_file():
    94     22.1 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     22.1 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     22.1 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     22.1 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     22.1 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     28.6 MiB      6.5 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     28.6 MiB     28.6 MiB   @profile
    93                             def _upload_file():
    94     28.6 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     28.6 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     28.6 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     28.6 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     28.6 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     34.7 MiB      6.1 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     34.7 MiB     34.7 MiB   @profile
    93                             def _upload_file():
    94     34.7 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     34.7 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     34.7 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     34.7 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     34.7 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     41.2 MiB      6.4 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2

Line #    Mem usage    Increment   Line Contents
================================================
    92     41.2 MiB     41.2 MiB   @profile
    93                             def _upload_file():
    94     41.2 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     41.2 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     41.2 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     41.2 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     41.2 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     47.4 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     47.4 MiB     47.4 MiB   @profile
    93                             def _upload_file():
    94     47.4 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     47.4 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     47.4 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     47.4 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     47.4 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     53.6 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     53.6 MiB     53.6 MiB   @profile
    93                             def _upload_file():
    94     53.6 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     53.6 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     53.6 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     53.6 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     53.6 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     59.8 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     59.8 MiB     59.8 MiB   @profile
    93                             def _upload_file():
    94     59.8 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     59.8 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     59.8 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     59.8 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     59.8 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     65.9 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2

Line #    Mem usage    Increment   Line Contents
================================================
    92     65.9 MiB     65.9 MiB   @profile
    93                             def _upload_file():
    94     65.9 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     65.9 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     65.9 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     65.9 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     65.9 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     72.1 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     72.1 MiB     72.1 MiB   @profile
    93                             def _upload_file():
    94     72.1 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     72.1 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     72.1 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     72.1 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     72.1 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     78.3 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     78.3 MiB     78.3 MiB   @profile
    93                             def _upload_file():
    94     78.3 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     78.3 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     78.3 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     78.3 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     78.3 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     84.8 MiB      6.4 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2

Line #    Mem usage    Increment   Line Contents
================================================
    92     84.8 MiB     84.8 MiB   @profile
    93                             def _upload_file():
    94     84.8 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     84.8 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     84.8 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     84.8 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     84.8 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     90.9 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92     90.9 MiB     90.9 MiB   @profile
    93                             def _upload_file():
    94     90.9 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     90.9 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     90.9 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     90.9 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     90.9 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100     97.1 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2

Line #    Mem usage    Increment   Line Contents
================================================
    92     97.1 MiB     97.1 MiB   @profile
    93                             def _upload_file():
    94     97.1 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95     97.1 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96     97.1 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98     97.1 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99     97.1 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100    103.3 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2

Line #    Mem usage    Increment   Line Contents
================================================
    92    103.3 MiB    103.3 MiB   @profile
    93                             def _upload_file():
    94    103.3 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95    103.3 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96    103.3 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98    103.3 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99    103.3 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100    109.5 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92    109.5 MiB    109.5 MiB   @profile
    93                             def _upload_file():
    94    109.5 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95    109.5 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96    109.5 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98    109.5 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99    109.5 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100    115.7 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92    115.7 MiB    115.7 MiB   @profile
    93                             def _upload_file():
    94    115.7 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95    115.7 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96    115.7 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98    115.7 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99    115.7 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100    122.1 MiB      6.4 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2

Line #    Mem usage    Increment   Line Contents
================================================
    92    122.1 MiB    122.1 MiB   @profile
    93                             def _upload_file():
    94    122.1 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95    122.1 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96    122.1 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98    122.1 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99    122.1 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100    128.3 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2


Line #    Mem usage    Increment   Line Contents
================================================
    92    128.3 MiB    128.3 MiB   @profile
    93                             def _upload_file():
    94    128.3 MiB      0.0 MiB       object_path = "/home/nnehdi/Desktop/6_meg_file.mp3"
    95    128.3 MiB      0.0 MiB       object_name = "test/6_meg_file.mp3"
    96    128.3 MiB      0.0 MiB       bucket_name = "tst"
    97                                 # file_data = io.open(object_path, mode='rb')
    98    128.3 MiB      0.0 MiB       file_size = os.stat(object_path).st_size
    99    128.3 MiB      0.0 MiB       with io.open(object_path, mode='rb') as file_data:
   100    134.5 MiB      6.2 MiB           return minio_client.put_object(bucket_name, object_name, file_data, file_size)


44a337cd3ec7fd833eb08f9b364a744a-2
```

**Comment by einali** [comment] 2018-02-18 07:59
Memory leak is blocking for production environment. pls fix it ASAP!

**Comment by harshavardhana** [comment] 2018-02-18 10:09
Duplicate of #595

**Comment by nnehdi** [comment] 2018-02-18 13:52
That's true, the problem appears when the files are larger than 5 Meg and uploading is done parallel.
We do not encounter with error noticed in issue #595 because our server's user process limit is high.
We are working on the problem.
tnx

**Comment by deekoder** [comment] 2018-03-01 22:55
I will close this one as a dup of the other issue then @nnehdi .

**Closed** 2018-03-01 22:55 UTC
Labels: duplicate, triage
