### ISSUE TITLE
api: Implement ListBucketPolicies 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#409] opened 2016-10-03 02:14 UTC

**Comment by indradhanush** [comment] 2017-02-13 16:31
@harshavardhana I could take a dig at this.

**Comment by harshavardhana** [comment] 2017-02-13 16:40
Thanks @indradhanush

**Comment by MrRedAmber** [comment] 2017-03-23 03:18
@indradhanush checking in, looking to pickup this issue.

**Comment by indradhanush** [comment] 2017-03-23 05:01
@MrRedAmber I haven't been able to get to this. :(
You can go ahead if you want. 👍

**Comment by harshavardhana** [comment] 2017-04-16 20:51
// cc @MrRedAmber is working on this and has a patch ready for us as well.

**Comment by deekoder** [comment] 2017-07-03 02:20
Waiting on @MrRedAmber  to respond on the open PR.

**Comment by kannappanr** [comment] 2018-01-18 18:57
Closing this issue as a duplicate of #611

**Closed by kannappanr** 2018-01-18 18:57 UTC
Labels: priority: medium
