### ISSUE TITLE
memorry error

### ISSUE THREAD

**Issue by rkdls** [minio/minio-py#607] opened 2018-01-03 02:52 UTC
if i upload so large file, there's occurred that memory error bellow

![1514946210](https://user-images.githubusercontent.com/9625741/34507706-25836618-f07c-11e7-8567-28498f8728e8.png)

i searched that line, minio-api looked like no close file description. i think.

so memory error occurred..

**Comment by harshavardhana** [comment] 2018-01-03 02:57
do you not have atleast 512MiB worth of memory? @rkdls

**Comment by rkdls** [comment] 2018-01-03 04:42
yes i do have 8GB memory size. @harshavardhana

**Comment by harshavardhana** [comment] 2018-01-03 05:18
This issue is another version of perhaps https://github.com/minio/minio-py/issues/595 

Few more questions
- how many objects did you upload before you saw this error?
- what is the file size that you were trying to upload?

**Comment by rkdls** [comment] 2018-01-03 06:39
- total file size 53.7GB
- total file number 2999
- error occurred in 2726/2999 which file size is 83.2MB

thank you for answer. !

**Comment by harshavardhana** [comment] 2018-01-03 07:09
> total file size 53.7GB
> total file number 2999
> error occurred in 2726/2999 which file size is 83.2MB

As expected #595 is the same reason why you have this issue ..

**Comment by rkdls** [comment] 2018-01-03 07:32
so.. it's not fixed yet?

**Comment by harshavardhana** [comment] 2018-01-03 07:33
> so.. it's not fixed yet?

no it is not fixed yet, we are working on it.  @rkdls

**Comment by kannappanr** [comment] 2018-01-03 18:51
Closing this as a duplicate of #595

**Closed by kannappanr** 2018-01-03 18:51 UTC
