### ISSUE TITLE
get_object via folder path from bucket is not possible

### ISSUE THREAD

**Issue by Vijayalaxmim** [minio/minio-py#690] opened 2018-08-24 08:28 UTC
I want to get a object which is stored in folders inside a bucket. For example ,inside a bucket bucket1, I want to access a object x from folder1/folder2/folder3/x
get_object and fget_object , both take bucket name and object name as parameter but not the path of object

**Comment by nitisht** [comment] 2018-08-24 08:35
can you try passing `folder1/folder2/folder3/x` as the object name

**Comment by Vijayalaxmim** [comment] 2018-08-24 08:41
I tried that. I got this exception "file is a directory."

**Comment by nitisht** [comment] 2018-08-24 08:42
can you paste a sample code snippet to help us reproduce this

**Comment by Vijayalaxmim** [comment] 2018-08-24 09:01
Hi , This issue can be closed ,I assumed the third parameter should be a folder where the file gets downloaded ,but it needs a file .And the error was with that parameter.
The error message could have been more clear

**Comment by nitisht** [comment] 2018-08-24 09:02
closing this as working as intended

**Closed by nitisht** 2018-08-24 09:02 UTC
Labels: priority: medium, triage
