### ISSUE TITLE
Bug - fput_object response http 409 bucketnotempty 

### ISSUE THREAD

**Issue by cheveyo20** [minio/minio-py#556] opened 2017-07-20 22:14 UTC
i tried to upload 300 files (each around 2mb) to minio server via fput object. It Works for all 299 except for one. Even after retrying it always fails for the same file. For some reason the respone code 409 says it can Not delete the bucket because its not empty. Why should Minio python try to delete the bucket the moment i call fput?! The file i cant upload has 2mb and is a png. Uploading via web interface chrome does work, so the file ist ok.

**Comment by vadmeste** [comment] 2017-07-24 18:09
hey @cheveyo20, sorry for the delay.

Are you still getting the error? if yes, could you give us a sample code which reproduces this issue?

Because I tried on my side and I was not able to reproduce it.

Thanks.

**Comment by harshavardhana** [comment] 2017-08-01 19:17
@cheveyo20 can you let us know if you still face this issue? . Feel free to close if its not a problem anymore.

**Comment by harshavardhana** [comment] 2017-08-07 16:45
> @cheveyo20 can you let us know if you still face this issue? . Feel free to close if its not a problem anymore.

Checking back again @cheveyo20 do you still face issue?

**Comment by deekoder** [comment] 2017-08-16 23:43
Closing this @cheveyo20  please reopen if its still happening.

**Closed by deekoder** 2017-08-16 23:43 UTC
Labels: priority: medium, triage, working as intended
